
# Site settings
title: ISHB
url: "http://ishb.us" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
description: > # this means to ignore newlines until "baseurl:"
  You can edit this line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# Build settings
markdown: kramdown
